# Generated by Django 4.0.5 on 2022-07-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeroplane', models.CharField(max_length=100)),
                ('departure_datetime', models.DateTimeField(auto_now_add=True)),
                ('arrival_datetime', models.DateTimeField(auto_now=True)),
                ('max_passengers', models.PositiveIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('difference', models.CharField(max_length=100)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='Airport.airport')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='Airport.airport')),
            ],
        ),
    ]
