# Generated by Django 4.0.5 on 2022-07-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='difference',
        ),
    ]
