# Generated by Django 4.0.5 on 2022-07-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_remove_flight_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(max_length=100),
        ),
    ]
