# Generated by Django 4.0.5 on 2022-07-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0004_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_duration', models.CharField(default=property, editable=False, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(),
        ),
    ]
