# Generated by Django 4.0.5 on 2022-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0005_duration_alter_flight_arrival_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='total_duration',
            field=models.CharField(default=property, editable=False, max_length=25),
        ),
    ]
