# Generated by Django 4.0.5 on 2022-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0006_delete_duration_flight_total_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='total_duration',
            field=models.CharField(default=property, max_length=25),
        ),
    ]
