# Generated by Django 4.0.5 on 2022-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0007_alter_flight_total_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['aeroplane', 'departure_datetime']},
        ),
    ]
